# Generated by Django 2.2.10 on 2020-05-03 03:16

import devices.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='favorit',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='devices',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=devices.models.upload_location),
        ),
    ]
