# Generated by Django 2.2.10 on 2020-05-03 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_auto_20200503_0416'),
    ]

    operations = [
        migrations.AddField(
            model_name='devices',
            name='ref',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
