# Generated by Django 2.2.10 on 2020-05-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_devices_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='ref',
            field=models.CharField(max_length=20),
        ),
    ]
