# Generated by Django 2.2.10 on 2020-05-06 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20200503_0428'),
    ]

    operations = [
        migrations.AddField(
            model_name='datas',
            name='battery',
            field=models.FloatField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
